---
- name: 'Import drain_node.yml playbook'
  ansible.builtin.import_tasks: drain_node.yml

- name: 'Import update_kernel.yml playbook'
  ansible.builtin.import_tasks: update_kernel.yml
  when: ready_to_drain == True

- name: 'Import update_kernel.yml playbook'
  ansible.builtin.import_tasks: restart_and_wait.yml
  when: ready_to_drain == True
