---
- name: 'Update apt cache'
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_pkg_mgr == "apt"

- name: 'Update dnf cache'
  ansible.builtin.dnf:
    update_cache: yes
  when: ansible_pkg_mgr == "dnf"

- name: 'Update all packages'
  ansible.builtin.package:
    name: '*'
    state: latest
